services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_HOST: "host.docker.internal"
      ENV: dev
    ports:
      - 6789:6789
    volumes:
      - ./mage:/home/src/
    restart: on-failure:5
    
